spring:
  application:
    name: techservice
  profiles:
      active: dev
  datasource:
        url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=false
        username: techservice
        password: techservice
  jpa:
      show-sql: true
  hibernate:
      ddl-auto: create
      naming:
        strategy: org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy
  data:
    mongodb:
      port: 27017
      database: serdar
  mail:
    host: smtp.gmail.com
    port: 25
    username: denememailsrd@gmail.com
    password: hasiktir
server:
    port: 8080
exampleApp:
  async:
    corePoolSize: 2
    maxPoolSize: 50
    queueCapacity: 10000
  mail:
    from: denememailsrd@gmail.com
