spring:
  application:
    name: techservice
  profiles:
      active: dev
  datasource:
        url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=false
        username: techservice
        password: techservice
  jpa:
      show-sql: true
  hibernate:
      ddl-auto: create
      naming:
        strategy: org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy
  data:
    mongodb:
      port: 27017
      database: serdar
  mail:
    host: smtp.gmail.com
    port: 587
    username: denememailsrd@gmail.com
    password: denememail
    protocol: smtp
    tls: true
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com
server:
    port: 8080
exampleApp:
  security:
    rememberMe:
      key: f1901d7e1c3e8c75bea8d43c601b71c17589b486
  async:
    corePoolSize: 2
    maxPoolSize: 50
    queueCapacity: 10000
  mail:
    from: denememailsrd@gmail.com
